// helper funtion to generate JSON parse tree from the parse tree generated by the parser
export function parseTreeToJson(node, parser) {
  if (!node) return null;

  if (node.children) {
    return {
      name: parser.ruleNames[node.ruleIndex] || "UNKNOWN",
      children: node.children.map((child) => parseTreeToJson(child, parser)),
    };
  } else {
    return { name: node.getText() };
  }
}
